from typing import Any
from vertx.eventbus import EventBus as EventBus, Payload as Payload

LOGGER: Any

class Client:
    eb: Any = ...
    def __init__(self, host: str, port: int) -> None: ...
    def parse(self, text: str) -> None: ...
    def quit(self) -> None: ...

def main() -> None: ...
